config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'likes/destroy'

  get 'posts/create'

  get 'posts/destroy'

  get 'static_pages/index' => 'static_pages#index'
  resources :friend_requests
  get 'static_pages/home' => 'static_pages#home'
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, :only => [:show, :index]
  resources :friends, :only => [:index, :destroy]
  resources :posts, :only => [:create, :destroy]
  resources :likes, :only => [:create, :destroy]
  resources :comments, :only => [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :friend_requests, dependent: :destroy
   has_many :pending_friends, through: :friend_requests, source: :friend #look for friend_id in Friendrequests
   #has_many :accept_requests, class_name: "FriendRequest", foreign_key: "friend_id", dependent: destroy
   #has_many :accept_friends, through: :accept_friends, 

   has_many :posts
   has_many :likes
   has_many :comments
   has_many :friendships, dependent: :destroy
   has_many :friends, through: :friendships
   devise :omniauthable, omniauth_providers: %i[facebook]


   def remove_friend(friend)
    friends.destroy(friend)
  end
  def feed
    Post.where("user_id IN (?) OR user_id = ?", friend_ids, id)
  end
  def liked?(post)
    if self.likes.find_by(post_id: post.id)
      true
    else 
      false
    end
  end
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
end
def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
def friends?(user)
  if self.friends.find_by(id: user.id)
    true
  else 
    false
  end
end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@posts = @user.posts.paginate(page: params[:page])
	end

	def index
		@users = User.paginate(page: params[:page])
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for (user, options = {size:80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/_conditions.html.erb
 <% if current_user != @user %>
 <% if current_user.friends.include?(@user) %>
 <p>Friends <i class="fa fa-check" aria-hidden="true"></i>
 </p>
 <br>
 <%= link_to "Delete friend", friend_path(@user), class: "btn btn-danger", method: :delete %>
 <% elsif current_user.pending_friends.include?(@user) %>
 <p> Friend Request Sent <i class="fa fa-spinner" aria-hidden="true"></i> </p>

 <% elsif @user.pending_friends.include?(current_user) %>
 <% request = FriendRequest.where({ friend: current_user, user_id: @user.id}) %>
 <%= link_to "Accept friend request", friend_request_path(request.first.id), method: :put, class: "btn btn-primary" %>
 <% else %>
 <%= link_to "Add friend", friend_requests_path(friend_id: @user.id), class: "btn btn-primary", method: :post%>
 <% end %>
 <%end%>

app/views/users/index.html.erb
<h2>Meet someone new</h2>
<%= will_paginate %>
<ul class="users">
	<% @users.each do |user| %>
	<% if !current_user.friends?(user) && current_user!=user %>
	<li>
		<%= gravatar_for user, size: 50%>
		<%= link_to user.name, user %>
	</li>
	<% end %>
<%end%>
</ul>
<%= will_paginate %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <br>
     <%= render 'users/conditions' %>
    </section>
    <section class = "stats">
      <%= render 'shared/profile' %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.posts.any? %>
      <h3>Posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>