config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'likes/destroy'

  get 'posts/create'

  get 'posts/destroy'

  get 'static_pages/index' => 'static_pages#index'
  resources :friend_requests
  get 'static_pages/home' => 'static_pages#home'
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, :only => [:show, :index]
  resources :friends, :only => [:index, :destroy]
  resources :posts, :only => [:create, :destroy]
  resources :likes, :only => [:create, :destroy]
  resources :comments, :only => [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
 validates :content, presence: true
 has_many :likes
 has_many :comments
 mount_uploader :picture, PictureUploader
   validate  :picture_size

  # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user,   only: :destroy
	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post created!"
			redirect_to root_url
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end
	def destroy
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to request.referrer || root_url
	end

	private
	def correct_user
		@post = current_user.posts.find_by(id: params[:id])
		redirect_to root_url if @post.nil?
	end
	def post_params
		params.require(:post).permit(:content, :picture)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
	<%= link_to gravatar_for(post.user, size: 50), post.user %>
	<span class="user"><%= link_to post.user.name, post.user %></span>
	<span class="content"><%= post.content %>
		<%= image_tag post.picture.url if post.picture? %>

	</span>
	<span class = "like">
		<% if current_user.liked?(post) %>
		<%= link_to "", like_path(post.id), class: "fa fa-thumbs-up", method: :delete %>
		<% else %>
		<%= link_to "", likes_path(post_id: post.id), class: "fa fa-thumbs-o-up", method: :post %>
		<% end %>
	</span>
	<span class = "comments">
		<% @comments = post.comments %>
		<span class = "iterations">
		<% @comments.each do |comment| %>
		<br>
		<li class = comment>
			<%= link_to gravatar_for(comment.user, size: 50), comment.user %>
			<span class="user"><%= link_to comment.user.name, comment.user %></span>
			<span class="content"><%= comment.content %>
			</span>
		</li>
		<br>
		<% end %>
	</span>
		<br>
		<div class="row">
			<div class = "col-md-4">
		<% @comment = Comment.new %>	
		<%= form_for(@comment) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="field">
			<%= f.text_area :content, placeholder: "Comment something!" %>
			<%= f.hidden_field :test_id, :value => post.id %>
		</div>
		<div class = "row">
			<div class = "col-md-4">
		<%= f.submit "Post", class: "btn btn-primary -sm" %>
	</div>
</div>
		<% end %>
	</div>
	</div>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(post.created_at) %> ago.
		<% if current_user == post.user  %>
		<%= link_to "delete", post, method: :delete,
		data: { confirm: "You sure?" } %>
		<% end %>
	</span>
</li>