config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'likes/destroy'

  get 'posts/create'

  get 'posts/destroy'

  get 'static_pages/index' => 'static_pages#index'
  resources :friend_requests
  get 'static_pages/home' => 'static_pages#home'
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, :only => [:show, :index]
  resources :friends, :only => [:index, :destroy]
  resources :posts, :only => [:create, :destroy]
  resources :likes, :only => [:create, :destroy]
  resources :comments, :only => [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :user_id, presence: true
	validates :post_id, presence: true
	validates :content, presence: true
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
	cattr_accessor :current_user
	belongs_to :user
	belongs_to :friend, class_name: "User"
	validates :user, presence: true
	validates :friend, presence: true, uniqueness: {scope: :user}
	validate :not_self
	validate :not_friends
	validate :not_pending
	#accept friendship, destroy request
	def accept
		user.friends << friend
		destroy
	end

	private
	def not_self
		errors.add(:friend, "can't be equal to user") if user == friend
	end
	def not_friends
		errors.add(:friend, 'is already added') if user.friends.include?(friend)
	end

	def not_pending
		errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
	end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, class_name: "User"

	after_create :create_inverse_relationship
	after_destroy :destroy_inverse_relationship

	private
	def create_inverse_relationship
    if friend.friendships.where(friend: user).blank?
      friend.friendships.create(friend: user)
    end
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
 validates :content, presence: true
 has_many :likes
 has_many :comments
 mount_uploader :picture, PictureUploader
   validate  :picture_size

  # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :friend_requests, dependent: :destroy
   has_many :pending_friends, through: :friend_requests, source: :friend #look for friend_id in Friendrequests
   #has_many :accept_requests, class_name: "FriendRequest", foreign_key: "friend_id", dependent: destroy
   #has_many :accept_friends, through: :accept_friends, 

   has_many :posts
   has_many :likes
   has_many :comments
   has_many :friendships, dependent: :destroy
   has_many :friends, through: :friendships
   devise :omniauthable, omniauth_providers: %i[facebook]


   def remove_friend(friend)
    friends.destroy(friend)
  end
  def feed
    Post.where("user_id IN (?) OR user_id = ?", friend_ids, id)
  end
  def liked?(post)
    if self.likes.find_by(post_id: post.id)
      true
    else 
      false
    end
  end
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
end
def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
def friends?(user)
  if self.friends.find_by(id: user.id)
    true
  else 
    false
  end
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@comment = current_user.comments.new
		@comment.post = Post.find_by(id: params[:comment][:test_id])
		@comment.content = params[:comment][:content]
		if @comment.save
			flash[:notice] = "Comment successful!"
			redirect_to root_path
		else
			flash[:alert] = "Failed to comment"
			redirect_to root_path
		end
	end
	def destroy
	end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :set_friend, only: :destroy
  before_action :authenticate_user!

  def index
    @friends = current_user.friends
  end
  def destroy
     current_user.remove_friend(@friend)
     flash[:notice] = "You are no longer friends with #{@friend.name}"
     redirect_to root_path
   end
 private

 def set_friend
  @friend = current_user.friends.find(params[:id])
end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!
	def create
		@like = current_user.likes.new
		@like.post = Post.find_by(id: params[:post_id])
		#debugger
		if @like.save
			flash[:notice] = "Liked Post!"
			redirect_to root_path
		else
			flash[:alert] = "Unable to like"
			redirect_to root_path
		end
	end

	def destroy
		@like = Like.find_by({ user: current_user, post_id: params[:id]})
		@like.destroy
		flash[:notice] = "Unliked Post!"
		redirect_to root_path
	end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user,   only: :destroy
	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post created!"
			redirect_to root_url
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end
	def destroy
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to request.referrer || root_url
	end

	private
	def correct_user
		@post = current_user.posts.find_by(id: params[:id])
		redirect_to root_url if @post.nil?
	end
	def post_params
		params.require(:post).permit(:content, :picture)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@posts = @user.posts.paginate(page: params[:page])
	end

	def index
		@users = User.paginate(page: params[:page])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for (user, options = {size:80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<strong>
		Made by: Karam Talwandi
	</strong>
	<nav>
		<ul>
			<li><a href="https://github.com/kpstalwa/friendbook" class="fa fa-github" target="_blank" style="font-size:36px;color:black"></a></li>
			<li><a href="https://www.linkedin.com/in/kpstalwa/" class="fa fa-linkedin" target="_blank" style="font-size:36px;color:black"></a><</li>
			<li><a href="mailto:k.talwandi@hotmail.com" class="fa fa-envelope" style="font-size:36px;color:black"></a>

			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="navigationbar">
<header class = "navbar navbar-fixed-top bg-primary">
	<div class ="container">
		<%= link_to "FriendBook", '#', id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", static_pages_home_path %></li>
				<% if user_signed_in? %>
				<li><%= link_to "Find Friends", users_path %></li>
				<li><%= link_to "Notifications", friend_requests_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						Account <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Settings", edit_user_registration_path %></li>
						<li class="divider"></li>
						<li>
							<%= link_to "Log out", destroy_user_session_path, method: :delete %>
						</li>
						<li class="divider"></li>
						<li> <%= link_to "Deactivate Account", '#', method: :delete, data: {confirm: "Are you sure you wish to delete your account?"} %>
						</li>
					</ul>
				</li>
				<%else%>
				<li><%= link_to "Log in", new_user_session_path %></li>
				<%end%>
			</ul>
		</nav>
	</div>

</header>

</div>
<!--
<div id="user_nav">
	<% if user_signed_in? %>
	Signed in as <%= current_user.email %>. Not you?
	<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	<% else %>
	<%= link_to "Sign up", new_user_registration_path %> or
	<%= link_to "Sign in", new_user_session_path %>
	<% end %>
</div>

-->

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Friendbook</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
	<%= render 'layouts/shim' %>
	<%= render 'layouts/nav' %>
	<div class="container">
		<%= render 'layouts/messages' %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-danger">
		This form contains <%= pluralize(object.errors.count, "error") %>.
	</div>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "What's on your mind?" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
  	<%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_profile.html.erb
<% @user ||= current_user %>
<% @friends = @user.friends %>

    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @friends.any? %>
      <div class="user_avatars">
        <% @friends.each do |user| %>
        <%= link_to gravatar_for(user, size: 30), user %>
        <% end %>
      </div>
      <% end %>
    </section>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <strong id="followers" class="stat">
      <%= link_to pluralize(@user.friends.count, "Friend"), static_pages_index_path %>
    </strong>
</div>